export const metadata = {
      title: 'Cookies | InBar Magazine',
        description: 'Zasady pouzivania cookies na InBar Magazine.',
        };

        export default function CookiesPage() {
          return (
              <main className="page-content">
                    <div className="container">
                            <div className="page-header">
                                      <h1>Cookies</h1>
                                                <div className="page-header-line" />
                                                        </div>

                                                                <div className="page-body">
                                                                          <p className="page-lead">
                                                                                      Tato stranka vysvetluje, co su cookies, ako ich pouzivame a ako ich mozete spravovat.
                                                                                                </p>

                                                                                                          <h2>Co su cookies</h2>
                                                                                                                    <p>
                                                                                                                                Cookies su male textove subory, ktore sa ukladaju vo Vasom prehliadaci pri navsteve webovej stranky.
                                                                                                                                            Pomahaju nam zapamatat si Vase nastavenia a zlepsit pouzivatelsky zazitok.
                                                                                                                                                      </p>

                                                                                                                                                                <h2>Ake cookies pouzivame</h2>
                                                                                                                                                                          <ul className="page-list">
                                                                                                                                                                                      <li>
                                                                                                                                                                                                    <strong>Nevyhnutne cookies</strong> - potrebne na spravne fungovanie stranky.
                                                                                                                                                                                                                  Bez nich stranka nemoze fungovat.
                                                                                                                                                                                                                              </li>
                                                                                                                                                                                                                                          <li>
                                                                                                                                                                                                                                                        <strong>Analyticke cookies</strong> - pomahaju nam pochopit, ako navstevnici
                                                                                                                                                                                                                                                                      pouzivaju stranku (napr. Google Analytics). Udaje su anonymizovane.
                                                                                                                                                                                                                                                                                  </li>
                                                                                                                                                                                                                                                                                              <li>
                                                                                                                                                                                                                                                                                                            <strong>Marketingove cookies</strong> - sluzja na zobrazovanie relevantnej reklamy.
                                                                                                                                                                                                                                                                                                                          Pouzivame ich len s Vasim suhasom.
                                                                                                                                                                                                                                                                                                                                      </li>
                                                                                                                                                                                                                                                                                                                                                </ul>

                                                                                                                                                                                                                                                                                                                                                          <h2>Sprava cookies</h2>
                                                                                                                                                                                                                                                                                                                                                                    <p>
                                                                                                                                                                                                                                                                                                                                                                                Cookies mozete kedykolvek zakazat alebo vymazat v nastaveniach Vasho prehliadaca.
                                                                                                                                                                                                                                                                                                                                                                                            Vypnutie cookies moze obmedzit niektore funkcie stranky.
                                                                                                                                                                                                                                                                                                                                                                                                      </p>
                                                                                                                                                                                                                                                                                                                                                                                                                <p>
                                                                                                                                                                                                                                                                                                                                                                                                                            Viac informacii o sprave cookies najdete na stranke{' '}
                                                                                                                                                                                                                                                                                                                                                                                                                                        <a href="https://www.allaboutcookies.org" target="_blank" rel="noreferrer">
                                                                                                                                                                                                                                                                                                                                                                                                                                                      allaboutcookies.org
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </a>.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <h2>Suhlas</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Pokracovanim v prehliadani tejto stranky suhlasiste s pouzivanim nevyhnutnych cookies.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Pre analyticke a marketingove cookies poziadame o Vas suhlas samostatne.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </p>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <p className="page-updated">Posledna aktualizacia: januar 2025</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
}